Homewrok for lecture 7.
kuweg/homework_repository_epam pull request #10
Opened 2021-12-08 15:05 UTC by kuweg

Lecture: https://github.com/kuweg/epam_python_autumn_2020/tree/main/lecture_07_idiomatic_python
Dear mentor,
Have a nice day!

2021-12-09 06:44 UTC, matacoder requested changes
Оптимизируй функцию.

2021-12-09 06:44 UTC, matacoder commented on homework7/hw1.py
> +    """Checks does a list contains a element with desired type."""
contain an element

2021-12-09 06:44 UTC, matacoder commented on homework7/hw1.py
> +    if type(child_value) not in [int, bool]:
Опять, объясняешь что делает функция, это понятно и так, глядя на нее и ее название, а вот зачем она это делает?

2021-12-09 06:44 UTC, matacoder commented on homework7/hw1.py
> +    all occurrences of element with desired type."""
Desire сильное слово, тут, наверное, requested подойдет.

2021-12-09 06:44 UTC, matacoder commented on homework7/hw1.py
> +def find_occurrences(tree: dict, desired_item) -> int:
А что если мы лист подадим на вход, а не строку?

2021-12-09 06:44 UTC, matacoder commented on homework7/hw2.py
> +    for char in string:
Иди с конца сразу по двум строкам и сравнивай последние символы, так как их невозможно удалить.
123456789012345678901234567890#######а
123456789012345678901234567890#######б
Эти две строки уже на первой итерации покажут, что они не равны, так как не равны последние символы.
А теперь представь, что у тебя 3 гб строка каждая.

2021-12-09 06:44 UTC, matacoder commented on homework7/hw2_long_solution.py
> +if __name__ == '__main__':
Это решение очень много памяти съест

2021-12-09 06:44 UTC, matacoder commented on homework7/hw3.py
> +def print_debugger(func) -> Callable:
Сделай себе модуль helpers.py и импортируй оттуда

2021-12-09 06:44 UTC, matacoder commented on homework7/hw3.py
> +# @print_debugger
Комментариев кода в коде быть не должно в общем случае

2021-12-09 06:44 UTC, matacoder commented on homework7/hw3.py
> +        diagonal = [matrix[matrix_size-i-1][i]
[matrix[i][-i-1] for i in range(matrix_size)]

2021-12-09 06:44 UTC, matacoder commented on homework7/hw3.py
> +        if all([move == player for move in board[i][:]]):
Делай set для любой буквы, и если длина set(letter) = 1 -  значит все буквы одинаковые.

2021-12-09 06:44 UTC, matacoder commented on homework7/hw3.py
> +    if all([move == player for move in get_diagonal(board)]):
Нагромождение условий, сделай кортеж со всеми комбинациями, и проверяй в нем.

2021-12-09 06:44 UTC, matacoder commented on homework7/hw3.py
> +def check_completeness(board: list, empty_symbol: str = '-') -> bool:
is_complete

2021-12-09 06:44 UTC, matacoder commented on homework7/hw3.py
> +    players = ['x', 'o']
с сетом было бы не важно какие у тебя там игроки

2021-12-09 06:44 UTC, matacoder commented on homework7/hw3.py
> +        return "o wins!"
просто верни победила буква такая-то, зачем конкретика

2021-12-09 11:56 UTC, kuweg commented on homework7/hw1.py
> +def find_occurrences(tree: dict, desired_item) -> int:
Функция выведет кол-во дочерних элементов, равное листу. В тестах проверка на это

2021-12-09 16:59 UTC, kuweg commented on homework7/hw3.py
> +        return "o wins!"
Задача просит возвращать строку

2021-12-10 06:28 UTC, matacoder commented on homework7/hw3.py
> +        return "o wins!"
Имел ввиду так:
if set(row) == 1:
    return f"The winner is {str(set(row))} player"

2021-12-10 06:29 UTC, matacoder commented on homework7/hw1.py
> +def find_occurrences(tree: dict, desired_item) -> int:
== или is?
А если внутри листа ссылка на самого себя?

2021-12-10 08:40 UTC, kuweg commented on homework7/hw3.py
> +        return "o wins!"
Так у меня примерно так и происходит в новой версии кода
if len(set(comb)) == 1:
            return f"{comb[0]} wins!"
Я в отдельной функции собираю комбинации, потом их проверяю.
Нашел небольшой баг, исправляю и загружаю

2021-12-10 08:41 UTC, kuweg commented on homework7/hw1.py
> +def find_occurrences(tree: dict, desired_item) -> int:
Действительно, is выглядит лучше

2021-12-10 08:59 UTC, kuweg commented on homework7/hw1.py
> +def find_occurrences(tree: dict, desired_item) -> int:
Я запутался, на вход функции приходит список, и мы хотим найти количество вхождений. Если это два одинаковых листа, то не получится их сравнить через is, так как у них разные адреса. Тогда почему == не подойдет?

2021-12-10 12:55 UTC, matacoder approved these changes
🥇

2021-12-10 12:55 UTC, matacoder commented on homework7/hw1.py
> +        return item == value
Объясни, зачем тебе такая сложная функция? Почему просто не вернуть == для этих двух значений, зачем ты сначала типы проверяешь?

2021-12-10 23:08 UTC, merged