Homework 8
kuweg/homework_repository_epam pull request #11
Opened 2021-12-13 21:41 UTC by kuweg

Lecture: https://github.com/kuweg/epam_python_autumn_2020/tree/main/lecture_08_object_model
Dear mentor,
have a nice day!

2021-12-14 08:18 UTC, matacoder requested changes
Хорошая работа, немного отшлифовать классы.

2021-12-14 08:18 UTC, matacoder commented on homework8/task1.py
> +            raise ValueError('Cannot be used as variable name!')
Молодец

2021-12-14 08:18 UTC, matacoder commented on homework8/task1.py
> +        with open(path_to_file, 'r') as file_handler:
А если файла не окажется?

2021-12-14 08:18 UTC, matacoder commented on homework8/task2.py
> +    def connect_to_database(self):
Можно было бы это сделать как @property

2021-12-14 08:18 UTC, matacoder commented on homework8/task2.py
> +        self.connection = sqlite3.connect(self.database_path)
Зачем дублировать, раз у тебя метод есть.

2021-12-15 12:38 UTC, kuweg commented on homework8/task2.py
> +        self.connection = sqlite3.connect(self.database_path)
Да, тут я попал в непонятную ситуацию с точки зрения проектирования.
Получается, что текущий код подключается к бд во время создания объекта, и метод connect_to_database() задумывался как запасной (если что-то пойдет не так).  Был вариант сделать так, чтобы в каждой функции вызывался connect и close, но он мне не понравился.

2021-12-15 12:52 UTC, matacoder commented on homework8/task2.py
> +        self.connection = sqlite3.connect(self.database_path)
Тебе нужен класс для подключения в БД, синглтон.

2021-12-16 08:27 UTC, matacoder reviewed
Хорошо, но можно лучше. Справишься с классом работы с БД? Будешь большим молодцом.

2021-12-16 08:27 UTC, matacoder commented on homework8/task2.py
> +    """Sigleton metaclass"""
Красота

2021-12-16 08:27 UTC, matacoder commented on homework8/task2.py
> +    connection = None
Можно же всегда создавать коннекшин, просто синглтон не даст создать второго.

2021-12-16 08:27 UTC, matacoder commented on homework8/task1.py
> +        """Overloaded __str__ for pretty print"""
Overloaded можно не писать, это ясно.

2021-12-16 08:27 UTC, matacoder commented on homework8/task2.py
> +        Database().close()
Вот это вроде бы и работает, но некрасиво. Все таки объект синглтона надо хранить и к нему обращаться.
То есть  объект коннекшина создай в ините, и передай уже в TableData, достав оттуда курсор и если нужно - закрой через точечную нотацию, но не по вызову класса.

2021-12-16 08:27 UTC, matacoder commented on homework8/task2.py
> +            f"SELECT * from {self.table_name} where name=:item", {"item": item}
А если у тебя сменится база данных? И там будет другой синтаксис?
В таких случаях делают класс-прокладку, где есть базовые методы для нужных операций.
class db
def contains
raise NotImplementedError
class sqlite(db)
def contains
SELECT * from ...

2021-12-16 15:23 UTC, kuweg commented on homework8/task2.py
> +            f"SELECT * from {self.table_name} where name=:item", {"item": item}
Получается, что такое же надо будет делать для соединения с бд?

2021-12-17 06:16 UTC, matacoder commented on homework8/task2.py
> +            f"SELECT * from {self.table_name} where name=:item", {"item": item}
Я думаю что соединение с бд можно инкапсулировать в сам класс работы с бд, а можно синглтоном. Еще раз, всегда представляй худшее - три бд, 3 разных языка, 1000 таблиц, 1000000 пользователей, файлы по 8 гб каждый. Чем хуже представишь реальность - тем лучше будет твой код.

2021-12-20 07:07 UTC, matacoder requested changes
Не нужно пересоединяться с БД при каждом запросе.

2021-12-20 07:07 UTC, matacoder commented on homework8/task1.py
> +                self.items[key] = int(value)
Он так не поймает отрицательные числа

2021-12-20 07:07 UTC, matacoder commented on homework8/task2.py
> +        with self.connection_manager() as cursor:
Каждый раз будет создавать новое соединение, обычно так не делают, подключение к БД должно быть синглтоном само по себе.

2021-12-20 07:07 UTC, matacoder commented on homework8/task2.py
> +    _select_template = 'SELECT * FROM {}'
Можно вынести в абстрактный класс как основа для реляционных баз данных, и если где-то будет иначе - в дочернем классе перезапишут.
Но за идею твердую пятерку. На проде такие запросы обычно вообще в отдельные файлы выносят.

2021-12-20 07:07 UTC, matacoder commented on homework8/task2.py
> +    presidents = TableData(db, "presidents")
вот сюда нужно коннекшн передавать уже готовый

2021-12-20 11:06 UTC, kuweg commented on homework8/task2.py
> +        with self.connection_manager() as cursor:
Эх, жаль, мне понравились контекстные менеджеры. Тогда я верну БД синглтон, но будут вызывать его в классе SQLiteClass

2021-12-20 11:24 UTC, matacoder commented on homework8/task2.py
> +        with self.connection_manager() as cursor:
Есть такое, изучаешь новую технологию и давай ее везде применять, сложно побороть.

2021-12-20 12:08 UTC, matacoder approved these changes
🥇

2021-12-20 12:08 UTC, matacoder commented on homework8/task2.py
> +class RelationalDataBase:
В конце слово Mixin добавь.

2021-12-20 12:08 UTC, matacoder commented on homework8/task2.py
> +    def __init__(self, Database, table_name) -> None:
Почему с большой буквы переменная?

2021-12-20 12:08 UTC, matacoder commented on homework8/task2.py
> +        return self.db.count(self.table_name)
Ты чувствуешь, насколько код стал взрослее?

2021-12-20 12:27 UTC, kuweg commented on homework8/task2.py
> +        return self.db.count(self.table_name)
Да, это ощущается

2021-12-20 12:38 UTC, merged