Homework 9.
kuweg/homework_repository_epam pull request #12
Opened 2021-12-19 13:14 UTC by kuweg

lecture: https://github.com/kuweg/epam_python_autumn_2020/tree/main/lecture_09_iterators
Dear mentor,
have a nice day!

2021-12-22 07:07 UTC, matacoder requested changes
ExitStack попробуй использовать. Это надежнее

2021-12-22 07:07 UTC, matacoder commented on homework9/hw1.py
> +    files = [open(fname, "r") for fname in file_list]
https://docs.python.org/3/library/contextlib.html#contextlib.ExitStack

2021-12-22 07:07 UTC, matacoder commented on homework9/utils/dummy_int.py
> +        Creating dummie diles in current directory.
files?

2021-12-22 07:07 UTC, matacoder commented on homework9/utils/dummy_int.py
> +                random.sample(range(0, 11), self.file_size)
Почему 11?

2021-12-22 07:07 UTC, matacoder commented on homework9/utils/dummy_int.py
> +        for i in range(self.n_files):
Мне кажется нужно вести список созданных файлов, чтобы потом по этому списку удалять. Всякое может произойти.

2021-12-22 07:07 UTC, matacoder commented on homework9/utils/dummy_int.py
> +    def get_paths(self, dir=None):
и вернул бы тут просто этот список

2021-12-22 07:07 UTC, matacoder commented on homework9/utils/dummy_int.py
> +        Decorator attempt.
Успешная попытка?

2021-12-22 07:07 UTC, matacoder commented on tests/homework9/test_hw1.py
> +def test_case_1():
Названия должны быть понятными

2021-12-22 07:07 UTC, matacoder commented on tests/homework9/test_hw2.py
> +        empty_list[2]
А он уже здесь выкинет, и дальше не пойдет

2021-12-22 07:07 UTC, matacoder commented on tests/homework9/test_hw2.py
> +        except IndexError:
Зачем так? Просто вызови массив с неправильным индексом, не нужен тебе трай тут.

2021-12-22 07:07 UTC, matacoder commented on tests/homework9/test_hw3.py
> +            dir_path=DIR_PATH, file_extension=EXTENSION, tokenizer=str.split
Нужно дополнительно токенайзер проверить, и желательно без операции IO.
У тебя нет варианта, где файл был бы:
1 2
3
4 5 6

2021-12-22 07:07 UTC, matacoder commented on homework9/hw3.py
> +        return sum(1 for _ in tokenizer(line))
А можно ли упростить до `sum(tokenizer(line))`?

2021-12-22 09:48 UTC, kuweg commented on tests/homework9/test_hw2.py
> +        except IndexError:
Да, я почему-то тогда подумал, что ошибку надо именно отловить

2021-12-22 09:48 UTC, kuweg commented on homework9/utils/dummy_int.py
> +        Decorator attempt.
Честно говоря не очень. Он как бы работает как декоратор, но не создает файлы где надо.

2021-12-22 10:05 UTC, kuweg commented on homework9/utils/dummy_int.py
> +        Decorator attempt.
Зато интересно, что так работает

2021-12-22 12:15 UTC, kuweg commented on homework9/hw3.py
> +        return sum(1 for _ in tokenizer(line))
Попробовал  - нельзя, нам же нужно посчитать кол-во токенов. В противном случае программа пытается сложить то, что не складывается

2021-12-22 12:40 UTC, kuweg commented on homework9/utils/dummy_int.py
> +        for i in range(self.n_files):
Сделал

2021-12-23 10:43 UTC, matacoder approved these changes
💯

2021-12-23 10:43 UTC, matacoder commented on homework9/hw3.py
> +        return sum(1 for _ in tokenizer(line))
len?

2021-12-23 11:09 UTC, kuweg commented on homework9/hw3.py
> +        return sum(1 for _ in tokenizer(line))
Ох, точно

2021-12-23 11:11 UTC, merged